[DEV-190648] Close custom tabs by redirect activity
TrustlyInc/trustly-react-native-example pull request #4
Opened 2023-09-19 20:46 UTC by andresguedes

A new Activity was added to call the main screen, after **urlScheme** was called. In this time, the **Chrome Custom Tabs** is open and the user needed to close it manually. Now, this will close automatically after the **urlScheme** trigger.

2023-09-20 11:53 UTC, marcosrivereto approved these changes
👍

2023-09-21 17:47 UTC, pedroabdenor approved these changes
👍

2023-10-09 18:00 UTC, lukevance requested changes
Everything worked as expected! I just have one question, do these changes need to be made manually in the Android app? If so, we should add notes to the primary readme page so people understand which modifications must be made.

2023-10-10 17:53 UTC, lukevance approved these changes
Looks good!

2023-10-10 17:53 UTC, lukevance commented on README.md
> +## Closing Chrome Custom Tab in Android
Perfect, thank you!

2023-10-10 17:58 UTC, merged