[DEV-207951] react native  render widget embedded on page
TrustlyInc/trustly-react-native-example pull request #7
Opened 2023-11-14 13:26 UTC by marcosrivereto

2023-12-12 20:24 UTC, pedroabdenor approved these changes
👍

2023-12-13 16:01 UTC, lukevance requested changes
This may not be important at the moment, so tell me what the effort level is here, but ideally the lightbox will launch when the user selects the bank as it does in our other example apps. If that's a major change we can consider leaving it like this for now, but the current implementation has this iOS component at the bottom of the screen that hides the "Pay" button after I select the bank. Can we fix that?

https://github.com/TrustlyInc/trustly-react-native-example/assets/13320316/934ba22d-fdb2-4d04-ba7b-139a83187e41

2023-12-14 12:43 UTC, marcosrivereto commented on src/trustly.tsx
> +  <script src="https://sandbox.trustly.one/start/scripts/pwmb.js?accessId=YOUR_ACCESS_ID>" type="text/javascript"></script>
Done

2023-12-14 12:43 UTC, marcosrivereto commented on src/trustly.tsx
> +  <script src="https://sandbox.trustly.one/start/scripts/pwmb.js?accessId=YOUR_ACCESS_ID>" type="text/javascript"></script>
Done

2023-12-15 20:00 UTC, lukevance approved these changes
Looks good and everything is working as expected now! 🥇

2023-12-15 20:00 UTC, lukevance commented on src/App.tsx
> +  ACCESS_ID = "<YOUR_ACCESS_ID>";
🙌

2023-12-15 20:00 UTC, lukevance commented on src/trustly.tsx
> +  <script src="https://sandbox.trustly.one/start/scripts/trustly.js?accessId=${accessId}" type="text/javascript"></script>
🕶️

2023-12-15 20:00 UTC, lukevance commented on src/trustly.tsx
> +export const lightbox = (accessId: String, data = {}) => `<!DOCTYPE html>
🦸

2023-12-15 20:06 UTC, merged